"use strict";

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    const now = new Date(); 
    await queryInterface.bulkInsert(
			'Flights',
			[
				{
					departure_airport_id: 1,
					arrival_airport_id: 2,
					airplane_id: 2,
					departure_date: new Date(now.getTime() + 1000 * 3600 * 24),
					arrival_date: new Date(now.getTime() + 1000 * 3600 * 24 * 2),
					price: 1500000,
					discount: 10,
					tax: 5,
					stock: 12,
					createdAt: new Date(),
					updatedAt: new Date(),
				},
				{
					departure_airport_id: 2,
					arrival_airport_id: 3,
					airplane_id: 3,
					departure_date: new Date(now.getTime() + 1000 * 3600 * 24),
					arrival_date: new Date(now.getTime() + 1000 * 3600 * 24 * 2),
					price: 1200000,
					discount: 10,
					tax: 5,
					stock: 63,
					createdAt: new Date(),
					updatedAt: new Date(),
				},
				{
					departure_airport_id: 3,
					arrival_airport_id: 4,
					airplane_id: 4,
					departure_date: new Date(now.getTime() + 1000 * 3600 * 24),
					arrival_date: new Date(now.getTime() + 1000 * 3600 * 24 * 2),
					price: 1000000,
					discount: 10,
					tax: 5,
					stock: 10,
					createdAt: new Date(),
					updatedAt: new Date(),
				},
				{
					departure_airport_id: 5,
					arrival_airport_id: 6,
					airplane_id: 5,
					departure_date: new Date(now.getTime() + 1000 * 3600 * 24),
					arrival_date: new Date(now.getTime() + 1000 * 3600 * 24 * 2),
					price: 1200000,
					discount: 10,
					tax: 5,
					stock: 10,
					createdAt: new Date(),
					updatedAt: new Date(),
				},
				{
					departure_airport_id: 6,
					arrival_airport_id: 7,
					airplane_id: 5,
					departure_date: new Date(now.getTime() + 1000 * 3600 * 24),
					arrival_date: new Date(now.getTime() + 1000 * 3600 * 24 * 2),
					price: 1000000,
					discount: 10,
					tax: 5,
					stock: 10,
					createdAt: new Date(),
					updatedAt: new Date(),
				},
				{
					departure_airport_id: 7,
					arrival_airport_id: 8,
					airplane_id: 6,
					departure_date: new Date(now.getTime() + 1000 * 3600 * 24),
					arrival_date: new Date(now.getTime() + 1000 * 3600 * 24 * 2),
					price: 1000000,
					discount: 10,
					tax: 5,
					stock: 10,
					createdAt: new Date(),
					updatedAt: new Date(),
				},
				{
					departure_airport_id: 8,
					arrival_airport_id: 9,
					airplane_id: 7,
					departure_date: new Date(now.getTime() + 1000 * 3600 * 24),
					arrival_date: new Date(now.getTime() + 1000 * 3600 * 24 * 2),
					price: 1000000,
					discount: 10,
					tax: 5,
					stock: 10,
					createdAt: new Date(),
					updatedAt: new Date(),
				},
				{
					departure_airport_id: 9,
					arrival_airport_id: 10,
					airplane_id: 8,
					departure_date: new Date(now.getTime() + 1000 * 3600 * 24),
					arrival_date: new Date(now.getTime() + 1000 * 3600 * 24 * 2),
					price: 1000000,
					discount: 10,
					tax: 5,
					stock: 10,
					createdAt: new Date(),
					updatedAt: new Date(),
				},
				{
					departure_airport_id: 10,
					arrival_airport_id: 11,
					airplane_id: 9,
					departure_date: new Date(now.getTime() + 1000 * 3600 * 24),
					arrival_date: new Date(now.getTime() + 1000 * 3600 * 24 * 2),
					price: 1000000,
					discount: 10,
					tax: 5,
					stock: 10,
					createdAt: new Date(),
					updatedAt: new Date(),
				},
				{
					departure_airport_id: 11,
					arrival_airport_id: 12,
					airplane_id: 10,
					departure_date: new Date(now.getTime() + 1000 * 3600 * 24),
					arrival_date: new Date(now.getTime() + 1000 * 3600 * 24 * 2),
					price: 1000000,
					discount: 10,
					tax: 5,
					stock: 10,
					createdAt: new Date(),
					updatedAt: new Date(),
				},
				{
					departure_airport_id: 10,
					arrival_airport_id: 9,
					airplane_id: 11,
					departure_date: new Date(now.getTime() + 1000 * 3600 * 24),
					arrival_date: new Date(now.getTime() + 1000 * 3600 * 24 * 2),
					price: 1000000,
					discount: 10,
					tax: 5,
					stock: 10,
					createdAt: new Date(),
					updatedAt: new Date(),
				},
				{
					departure_airport_id: 5,
					arrival_airport_id: 8,
					airplane_id: 12,
					departure_date: new Date(now.getTime() + 1000 * 3600 * 24),
					arrival_date: new Date(now.getTime() + 1000 * 3600 * 24 * 2),
					price: 1000000,
					discount: 10,
					tax: 5,
					stock: 10,
					createdAt: new Date(),
					updatedAt: new Date(),
				},
			],
			{}
		);
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete("Flights", null, {});
  },
};
